## Exploratory Data Analysis and Feature Engineering

In [4]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import VarianceThreshold

print("All libraries imported successfully")

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
  File "/var/folders/cs/xrtnc08x2x38q56mjr45br240000gn/T/ipykernel_56860/732934604.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/pygments/styles/__init__.py", line 45, in get_style_by_name
ModuleNotFoundError: No module named 'pygments.styles.default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2144, in showtraceback
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1173, in structured_traceback
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1063, in format_exception_as_a_whole
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1114, in get_records
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/pygments/styles/__init__.py", line 47, in get_style_by_name
pygments.util.ClassNotFound: Could not find style module 'pygments.styles.default', though it should be builtin.

### Data Import and Overview

The first part of the EDA is confirming data columns and information. Next is a simple data cleaning, merging the sets and finally a thorough cleaning process, and some exploratory analysis of the dataset.

In [ ]:
df1 = pd.read_csv("../data/raw/NP_dataset.csv")
df2 = pd.read_csv("../data/raw/NP_dataset_small_molecules.csv")
df3 = pd.read_csv("../data/raw/NP_dataset_formulations.csv")
df4 = pd.read_excel("../data/raw/mp_dataset_initial.xlsx")
print("All datasets loaded successfully")

All datasets loaded successfully

In [ ]:
print(f"Df1 shape: {df1.shape}")  
df1.head()

Df1 shape: (433, 18)

,polymer_MW,LA/GA,mol_MW,mol_logP,mol_TPSA,mol_melting_point,mol_Hacceptors,mol_Hdonors,mol_heteroatoms,drug/polymer,surfactant_concentration,surfactant_HLB,aqueous/organic,pH,solvent_polarity_index,particle_size,EE,LC
0,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,1.00,1.5,18.0,4.0,0,5.1,210.0,25.18,20.12
1,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,0.50,1.5,18.0,4.0,0,5.1,198.0,44.83,18.31
2,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,0.20,1.5,18.0,4.0,0,5.1,190.0,51.83,9.39
3,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,0.10,1.5,18.0,4.0,0,5.1,181.0,86.60,7.97
4,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,0.05,1.5,18.0,4.0,0,5.1,232.0,60.60,2.94

In [ ]:
print(f"Df2 shape: {df2.shape}") 
df2.head()

Df2 shape: (65, 3)

,small_molecule_name,canonical_SMILES,mol_melting_point
0,sparfloxacin,O=C(O)C1=CN(C2=C(F)C(=C(F)C(N)=C2C1=O)N3CC(NC(...,267.5
1,diazepam,O=C1N(C=2C=CC(Cl)=CC2C(=NC1)C=3C=CC=CC3)C,132.0
2,rivastigmine-tartrate,O=C(O)C(O)C(O)C(=O)O.O=C(OC1=CC=CC(=C1)C(N(C)C...,123.5
3,flurbiprofen,O=C(O)C(C=1C=CC(=C(F)C1)C=2C=CC=CC2)C,110.1
4,docetaxel,O=C(OC(C)(C)C)NC(C=1C=CC=CC1)C(O)C(=O)OC2C(=C3...,232.0

In [ ]:
print(f"Df3 shape: {df3.shape}") 
df3.head()

Df3 shape: (433, 13)

,reference,small_molecule_name,surfactant_name,solvent,polymer_MW,LA/GA,drug/polymer,surfactant_concentration,aqueous/organic,pH,particle_size,EE,LC
0,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone,14.0,1.0,1.00,1.5,4.0,0,210.0,25.18,20.12
1,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone,14.0,1.0,0.50,1.5,4.0,0,198.0,44.83,18.31
2,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone,14.0,1.0,0.20,1.5,4.0,0,190.0,51.83,9.39
3,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone,14.0,1.0,0.10,1.5,4.0,0,181.0,86.60,7.97
4,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone,14.0,1.0,0.05,1.5,4.0,0,232.0,60.60,2.94

In [ ]:
print(f"Df4 shape: {df4.shape}")
df4.head()

Df4 shape: (4913, 17)

,Formulation Index,Drug,Drug SMILES,Polymer Mw,Polymer Mn,Polymer Molecular Weight (unit not specified),PDI,LA/GA,Formulation Method,Initial Drug-to-Polymer Ratio,Particle Size,Drug Loading Capacity,Drug Encapsulation Efficiency,Solubility Enhancer Concentration,Time,Release,DOI
0,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,0.000000,0.000000,10.3390/ijms241914729
1,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,1.889764,0.062622,10.3390/ijms241914729
2,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,7.181102,0.056751,10.3390/ijms241914729
3,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,13.984252,0.058708,10.3390/ijms241914729
4,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,27.968504,0.058708,10.3390/ijms241914729

Checking for column and data types so we know what matches, what columns have the same content but different names and what columns to drop.

In [ ]:
for i, df in enumerate([df1, df2, df3, df4], 1):
    print(f"\nDataset {i}")
    print(df.dtypes)

Dataset 1
polymer_MW                  float64
LA/GA                       float64
mol_MW                      float64
mol_logP                    float64
mol_TPSA                    float64
mol_melting_point           float64
mol_Hacceptors                int64
mol_Hdonors                   int64
mol_heteroatoms               int64
drug/polymer                float64
surfactant_concentration    float64
surfactant_HLB              float64
aqueous/organic             float64
pH                            int64
solvent_polarity_index      float64
particle_size               float64
EE                          float64
LC                          float64
dtype: object

Dataset 2
small_molecule_name     object
canonical_SMILES        object
mol_melting_point      float64
dtype: object

Dataset 3
reference                    object
small_molecule_name          object
surfactant_name              object
solvent                      object
polymer_MW                  float64
LA/GA                       float64
drug/polymer                float64
surfactant_concentration    float64
aqueous/organic             float64
pH                            int64
particle_size               float64
EE                          float64
LC                          float64
dtype: object

Dataset 4
Formulation Index                                  int64
Drug                                              object
Drug SMILES                                       object
Polymer Mw                                       float64
Polymer Mn                                       float64
Polymer Molecular Weight (unit not specified)    float64
PDI                                              float64
LA/GA                                            float64
Formulation Method                                object
Initial Drug-to-Polymer Ratio                    float64
Particle Size                                    float64
Drug Loading Capacity                            float64
Drug Encapsulation Efficiency                    float64
Solubility Enhancer Concentration                float64
Time                                             float64
Release                                          float64
DOI                                               object
dtype: object

From the columns, It is noticeable that some columns have the same data but different names. The next step is to standardize the column names. 

The columns that match include: 
- particle size, pH, surfactant concentration, small molecule name, LA/GA, polymer MW acqueouss/organic.

Columns with same content but different names include: 

- Drug-to-polymer ratio, drug encapusulation efficiency, loading capacity, Smiles, PDI, surfactant concentration, molecule name. 

Dataset 4 requires the most adjustment based on this analysis. The other tables have similar names, with a difference in size of data acquired. 

Before we start working on the data, I will copy the tables to thhe processed folder so that the raw data can stay intact for reference and incase any irreversible issues arise later on.

In [ ]:
datasets = {
    "dataset1.csv": df1,
    "dataset2.csv": df2,
    "dataset3.csv": df3,
    "dataset4.csv": df4 } 

for filename, dataframe in datasets.items():
    path = os.path.join("../data/processed/", filename)
    dataframe.to_csv(path, index=False)
print("All datasets saved in processed folder")

All datasets saved in processed folder

In [ ]:
#using the processed datasets going forward
df1 = pd.read_csv("../data/processed/dataset1.csv")
df2 = pd.read_csv("../data/processed/dataset2.csv")
df3 = pd.read_csv("../data/processed/dataset3.csv")
df4 = pd.read_csv("../data/processed/dataset4.csv")

In [ ]:
df4 = df4.rename(columns={"Particle Size": "particle_size", "Polymer MW": "polymer_MW", "Solubility Enhancer Concentration": "surfactant_concentration", "Drug Loading Capacity": "LC",
    "Drug Encapsulation Efficiency": "EE","Drug":"small_molecule_name", "Initial Drug-to-Polymer Ratio": "drug/polymer", "Drug SMILES": "canonical_SMILES", "Encapsulation Efficiency (%)": "encapsulation_efficiency_percent"})
df4.head()

,Formulation Index,small_molecule_name,canonical_SMILES,Polymer Mw,Polymer Mn,Polymer Molecular Weight (unit not specified),PDI,LA/GA,Formulation Method,drug/polymer,particle_size,LC,EE,surfactant_concentration,Time,Release,DOI
0,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,0.000000,0.000000,10.3390/ijms241914729
1,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,1.889764,0.062622,10.3390/ijms241914729
2,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,7.181102,0.056751,10.3390/ijms241914729
3,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,13.984252,0.058708,10.3390/ijms241914729
4,1,moxidectin,CC1CC(=CCC2CC(CC3(O2)CC(=NOC)C(C(O3)C(=CC(C)C)...,75.0,NaN,NaN,NaN,3.0,O/W,0.666667,47.723,35.41,88.3,0.5,27.968504,0.058708,10.3390/ijms241914729

Before merging, we have to ensure all text columns that overlap are in lower case.

In [ ]:
df2["small_molecule_name"] = df2["small_molecule_name"].str.strip().str.lower()
df3["small_molecule_name"] = df3["small_molecule_name"].str.strip().str.lower()
df4["small_molecule_name"] = df4["small_molecule_name"].str.strip().str.lower()
print("Small molecule names standardized in both datasets")

Small molecule names standardized in both datasets

Confirm all tables and look for any missed similarities.

In [ ]:
# Pairwise common columns (this is the most important part)
print("\nPairwise Common Columns\n")

pairs = [(df1, df2, 'df1', 'df2'),
         (df1, df3, 'df1', 'df3'),
         (df1, df4, 'df1', 'df4'),
         (df2, df3, 'df2', 'df3'),
         (df2, df4, 'df2', 'df4'),
         (df3, df4, 'df3', 'df4')]

for dfa, dfb, name_a, name_b in pairs:
    common = sorted(set(dfa.columns) & set(dfb.columns))
    print(f"Common columns between {name_a} and {name_b}:")
    print(common if common else "None")
    print(f"   → Count: {len(common)}\n")

# Columns that appear in ALL 4 dataframes (usually very few or empty)
common_all = set(df1.columns) & set(df2.columns) & set(df3.columns) & set(df4.columns)
print(" Columns present in ALL 4 dataframes")
print(sorted(common_all) if common_all else "None (this is normal)")

Pairwise Common Columns

Common columns between df1 and df2:
['mol_melting_point']
   → Count: 1

Common columns between df1 and df3:
['EE', 'LA/GA', 'LC', 'aqueous/organic', 'drug/polymer', 'pH', 'particle_size', 'polymer_MW', 'surfactant_concentration']
   → Count: 9

Common columns between df1 and df4:
['EE', 'LA/GA', 'LC', 'drug/polymer', 'particle_size', 'surfactant_concentration']
   → Count: 6

Common columns between df2 and df3:
['small_molecule_name']
   → Count: 1

Common columns between df2 and df4:
['canonical_SMILES', 'small_molecule_name']
   → Count: 2

Common columns between df3 and df4:
['EE', 'LA/GA', 'LC', 'drug/polymer', 'particle_size', 'small_molecule_name', 'surfactant_concentration']
   → Count: 7

 Columns present in ALL 4 dataframes
None (this is normal)

In [ ]:
# Column overlap between D1 and D3
common_cols = set(df1.columns) & set(df3.columns)
print(f"\nCommon columns: {common_cols}")

# Check exact column names (case, underscores matter)
print(f"\nD1 columns: {df1.columns.tolist()}")
print(f"D3 columns: {df3.columns.tolist()}")

print(f"Df1 shape: {df1.shape}")  
print(f"Df3 shape: {df3.shape}")

Common columns: {'LC', 'aqueous/organic', 'surfactant_concentration', 'particle_size', 'EE', 'polymer_MW', 'drug/polymer', 'pH', 'LA/GA'}

D1 columns: ['polymer_MW', 'LA/GA', 'mol_MW', 'mol_logP', 'mol_TPSA', 'mol_melting_point', 'mol_Hacceptors', 'mol_Hdonors', 'mol_heteroatoms', 'drug/polymer', 'surfactant_concentration', 'surfactant_HLB', 'aqueous/organic', 'pH', 'solvent_polarity_index', 'particle_size', 'EE', 'LC']
D3 columns: ['reference', 'small_molecule_name', 'surfactant_name', 'solvent', 'polymer_MW', 'LA/GA', 'drug/polymer', 'surfactant_concentration', 'aqueous/organic', 'pH', 'particle_size', 'EE', 'LC']
Df1 shape: (433, 18)
Df3 shape: (433, 13)

From the little EDA we can tell that dataset 1 and dataset 3 are. almost certainly the same experiment. Dataset 1 has additional drug molecular properties and dataset 3 has drug name and experimental details.

In [ ]:
# Checking if rows align exactly on shared numeric columns
shared_cols = ['aqueous/organic', 'pH', 'drug/polymer', 'surfactant_concentration', 'particle_size', 'LA/GA', 'LC', 'polymer_MW', 'EE']

# Test first few rows
for col in shared_cols:
    if col in df1.columns and col in df3.columns:
        # Check if values match (allowing small float tolerance)
        matches = np.isclose(df1[col].values, df3[col].values, rtol=1e-5, atol=1e-8)
        print(f"{col}: {matches.sum()}/{len(matches)} matches ({matches.sum()/len(matches)*100:.1f}%)")
        
        if matches.sum() < len(matches):
            print(f"  → Mismatch at indices: {np.where(~matches)[0][:5]}")

# If mismatches exist, sort both by a compound key first
any_mismatch = False
if any_mismatch:
    sort_keys = ['polymer_MW', 'LA/GA', 'drug/polymer']
    df1_sorted = df1.sort_values(by=sort_keys).reset_index(drop=True)
    df3_sorted = df3.sort_values(by=sort_keys).reset_index(drop=True)
else:
    df1_sorted = df1.reset_index(drop=True)
    df3_sorted = df3.reset_index(drop=True)

aqueous/organic: 433/433 matches (100.0%)
pH: 433/433 matches (100.0%)
drug/polymer: 433/433 matches (100.0%)
surfactant_concentration: 433/433 matches (100.0%)
particle_size: 433/433 matches (100.0%)
LA/GA: 433/433 matches (100.0%)
LC: 433/433 matches (100.0%)
polymer_MW: 433/433 matches (100.0%)
EE: 433/433 matches (100.0%)

We have now confirmed that the content in dataset 1 and dataset 3 are the same (they were derived from the same research). Merging them is the next step.

#### Merging step

In [ ]:
df13.head()

,polymer_MW,LA/GA,mol_MW,mol_logP,mol_TPSA,mol_melting_point,mol_Hacceptors,mol_Hdonors,mol_heteroatoms,drug/polymer,...,aqueous/organic,pH,solvent_polarity_index,particle_size,EE,LC,reference,small_molecule_name,surfactant_name,solvent
0,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,1.00,...,4.0,0,5.1,210.0,25.18,20.12,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone
1,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,0.50,...,4.0,0,5.1,198.0,44.83,18.31,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone
2,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,0.20,...,4.0,0,5.1,190.0,51.83,9.39,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone
3,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,0.10,...,4.0,0,5.1,181.0,86.60,7.97,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone
4,14.0,1.0,392.41,2.08,100.59,267.5,6,3,9,0.05,...,4.0,0,5.1,232.0,60.60,2.94,10.1016/j.nano.2009.10.004,sparfloxacin,PVA,acetone

In [17]:
# Check common columns between df13 and the other two tables
print("Common columns between df13 and df2:")
print(sorted(set(df13.columns) & set(df2.columns)))

print("\nCommon columns between df13 and df4:")
print(sorted(set(df13.columns) & set(df4.columns)))

print("\nCommon columns between df2 and df4:")
print(sorted(set(df2.columns) & set(df4.columns)))

Common columns between df13 and df2:
['mol_melting_point', 'small_molecule_name']

Common columns between df13 and df4:
['EE', 'LA/GA', 'LC', 'drug/polymer', 'particle_size', 'small_molecule_name', 'surfactant_concentration']

Common columns between df2 and df4:
['canonical_SMILES', 'small_molecule_name']

Checking quality and similarity in data between df13 and df4 before merging.

In [1]:
merge_keys = ['small_molecule_name', 'LA/GA', 'drug/polymer', 
              'surfactant_concentration', 'particle_size']

print("Checking Alignment Between df13 and df4\n")
print(f"Using merge keys: {merge_keys}\n")

# Find rows in df13 that would not find a match in df4
unmapped = []

for idx, row in df13.iterrows():
    mask = True
    for key in merge_keys:
        if key in df4.columns:
            mask = mask & (df4[key] == row[key])
        else:
            mask = False
            break
    
    if not mask.any():          
        unmapped.append(idx)

print(f"Rows in df13 with NO matching key combination in df4 : {len(unmapped)} / {len(df13)}")
print(f"Match rate: {(len(df13) - len(unmapped)) / len(df13) * 100:.1f}%")

# Check the opposite direction (rows in df4 with no match in df13)
print("\n" + "-"*70)
print("Checking opposite direction (df4 to df13)...")
unmapped_df4 = []
for idx, row in df4.iterrows():
    mask = True
    for key in merge_keys:
        mask = mask & (df13[key] == row[key])
    if not mask.any():
        unmapped_df4.append(idx)

print(f"Rows in df4 with NO matching key combination in df13: {len(unmapped_df4)} / {len(df4)}")

# Summary
if len(unmapped) > len(df13) * 0.25:
    print("\nHigh mismatch rate detected")
else:
    print("\n Relatively good alignment.")

Checking Alignment Between df13 and df4

Using merge keys: ['small_molecule_name', 'LA/GA', 'drug/polymer', 'surfactant_concentration', 'particle_size']

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
  File "/var/folders/cs/xrtnc08x2x38q56mjr45br240000gn/T/ipykernel_56860/241730508.py", line 10, in <module>
    for idx, row in df13.iterrows():
NameError: name 'df13' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/pygments/styles/__init__.py", line 45, in get_style_by_name
ModuleNotFoundError: No module named 'pygments.styles.default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2144, in showtraceback
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1173, in structured_traceback
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1063, in format_exception_as_a_whole
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1114, in get_records
  File "/Users/eunice/Documents/2026/4B/459/PLGA/plga_venv/lib/python3.9/site-packages/pygments/styles/__init__.py", line 47, in get_style_by_name
pygments.util.ClassNotFound: Could not find style module 'pygments.styles.default', though it should be builtin.

In [ ]:
# notebooks/01_data_exploration.ipynb

from src.data_loader import DataLoader

loader = DataLoader(data_path='../data/processed/')

df13 = loader.load_df13()
print("Base df13 (D1 + D3):", df13.shape)
df13.head()

df13_with_smiles = loader.load_df13_with_smiles()
print("\nWith SMILES:", df13_with_smiles.shape)
df13_with_smiles[['small_molecule_name', 'canonical_SMILES']].head()

# Option 3: Build everything from scratch (if files don't exist)
df13_complete = loader.prepare_full_dataset()